
# node js - version

FROM node:24-alpine3.21

#make new folder

WORKDIR /app/btvn-day46

#copy from(folder of pc) to (folder of docker)

#COPY . /app/btvn-day46

# cai thu vien

#RUN npm i

# chay app

#CMD ["npm", "run", "dev"]